In [28]:
import numpy as np
import pandas as pd

In [27]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,12,0]],columns = ['CGPA','Profile_score','placed'])

In [29]:
df

,CGPA,Profile_score,placed
0,8,8,1
1,7,9,1
2,6,10,0
3,5,12,0


In [30]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [31]:
from pandas.core.tools.datetimes import ArrayConvertible
model  = Sequential()

model.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [32]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [33]:
model.get_weights()

[array([[ 0.4647994 ,  0.17165709],
        [ 1.1176833 , -0.10753524]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 1.1979755 ],
        [-0.38292575]], dtype=float32),
 array([0.], dtype=float32)]

In [34]:
new_wights = [np.array([[ 0.1,0.1],
        [0.1 , 0.1 ]], dtype=np.float32),
     np.array([0., 0.], dtype=np.float32),
     np.array([[0.1],
        [ 0.1]], dtype=np.float32),
     np.array([0.], dtype=np.float32)]

In [35]:
model.set_weights(new_wights)
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [37]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy',optimizer= optimizer)

In [39]:
model.fit(df.iloc[:,0:-1].values,df['placed'].values,epochs=75,verbose=1,batch_size =1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.6984 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6974 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6973 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6975 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6973 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6969 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6969 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6968 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6970 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6967 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6968 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6965 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6965 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6965 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6965 
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━━

In [40]:
model.get_weights()

[array([[0.12337606, 0.12337606],
        [0.04062007, 0.04062007]], dtype=float32),
 array([-0.02279737, -0.02279737], dtype=float32),
 array([[0.08243153],
        [0.08243153]], dtype=float32),
 array([-0.01909722], dtype=float32)]